name: data_on_fhir
description: Easily Convert Tabular CSV Data Into FHIR
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  csv: ^5.1.0
  fhir: ^0.11.4
  flutter:
    sdk: flutter
  gsheets: ^0.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/fire.jpeg
